# conf/model/lightgbm.yaml

_target_: src.models.onerride_ml.LGBMWrapper

# --- 学習制御 ---
num_boost_round: 2000
early_stopping_rounds: 50
verbose_eval: 100

# --- LightGBM ハイパーパラメータ ---
params:
  objective: "regression"
  metric: "rmse"
  boosting_type: "gbdt"
  learning_rate: 0.05
  num_leaves: 31
  max_depth: -1
  feature_fraction: 0.8 # 特徴量のサンプリング（過学習防止）
  bagging_fraction: 0.8 # データのサンプリング
  bagging_freq: 5
  seed: 42
  verbosity: -1
  n_jobs: -1 # CPU全コア使用
